import { Bookmark, BookmarkCheck, ChevronDown, X } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import type { Insight } from "../../api/types";
import { formatAmountSigned } from "../../lib/money";
import { Text } from "../../ui";
import {
  actionRoute,
  EVIDENCE_LABELS,
  INSIGHT_ICONS,
  INSIGHT_KIND_LABELS,
  MONEY_EVIDENCE_KEYS,
  SEVERITY_LABELS,
} from "./insightMeta";

/**
 * One insight from the coach.
 *
 * The design decision that matters here is that **"why" is a first-class part
 * of the card, not a tooltip**. Every insight carries a rationale from the
 * backend by contract, and this surfaces it behind a single disclosure
 * alongside the figures it was computed from.
 *
 * That's what separates a coach from a nag: a user who can check one claim
 * will believe the next. It also keeps the product honest as an LLM is added
 * later — a model-authored insight has to fill the same slot, so it can't
 * assert something it has no numbers for.
 */
export function InsightCard({
  insight,
  currency,
  onDismiss,
  onBookmark,
}: {
  insight: Insight;
  currency: string;
  onDismiss?: (id: string) => void;
  onBookmark?: (id: string) => void;
}) {
  const [showWhy, setShowWhy] = useState(false);
  const Icon = INSIGHT_ICONS[insight.kind] ?? INSIGHT_ICONS.health_improvement;
  const route = actionRoute(insight.action);
  const bookmarked = insight.status === "bookmarked";

  // Only keys we have labels for. Dumping an opaque dict would defeat the
  // point of evidence, which is that it can be read.
  const evidence = Object.entries(insight.evidence ?? {}).filter(
    ([key, value]) => key in EVIDENCE_LABELS && (typeof value === "number" || typeof value === "string"),
  );

  return (
    <article className="lf-insight" data-severity={insight.severity}>
      <div className="lf-insight-head">
        <span className="lf-insight-icon" aria-hidden="true">
          <Icon size={16} strokeWidth={1.9} />
        </span>
        <div className="lf-insight-heading">
          <p className="lf-insight-kind">
            {INSIGHT_KIND_LABELS[insight.kind] ?? "Insight"}
            <span className="lf-insight-severity">{SEVERITY_LABELS[insight.severity]}</span>
          </p>
          <h3 className="lf-insight-title">{insight.title}</h3>
        </div>

        <div className="lf-insight-actions">
          {onBookmark && (
            <button
              type="button"
              className="lf-btn lf-btn--ghost lf-iconbtn"
              onClick={() => onBookmark(insight.id)}
              aria-label={bookmarked ? "Bookmarked" : "Bookmark this insight"}
              aria-pressed={bookmarked}
            >
              {bookmarked ? (
                <BookmarkCheck size={15} strokeWidth={1.9} aria-hidden="true" />
              ) : (
                <Bookmark size={15} strokeWidth={1.9} aria-hidden="true" />
              )}
            </button>
          )}
          {onDismiss && (
            <button
              type="button"
              className="lf-btn lf-btn--ghost lf-iconbtn"
              onClick={() => onDismiss(insight.id)}
              aria-label="Dismiss this insight"
            >
              <X size={15} strokeWidth={1.9} aria-hidden="true" />
            </button>
          )}
        </div>
      </div>

      <p className="lf-insight-body">{insight.body}</p>

      <div className="lf-insight-foot">
        {route && (
          <Link className="lf-btn lf-btn--secondary lf-btn--sm" to={route.to}>
            {route.label}
          </Link>
        )}
        <button
          type="button"
          className="lf-insight-why-toggle"
          onClick={() => setShowWhy((v) => !v)}
          aria-expanded={showWhy}
        >
          Why am I seeing this?
          <ChevronDown size={14} strokeWidth={2} aria-hidden="true" data-open={showWhy || undefined} />
        </button>
      </div>

      {showWhy && (
        <div className="lf-insight-why">
          <p>{insight.rationale}</p>

          {evidence.length > 0 && (
            <dl className="lf-insight-evidence">
              {evidence.map(([key, value]) => (
                <div key={key}>
                  <dt>{EVIDENCE_LABELS[key]}</dt>
                  <dd>
                    {MONEY_EVIDENCE_KEYS.has(key) && typeof value === "number"
                      ? formatAmountSigned(value, currency)
                      : String(value)}
                  </dd>
                </div>
              ))}
            </dl>
          )}

          {/* Provenance in plain sight. Once an LLM can author these, knowing
              which engine produced a claim stops being a nicety. */}
          <Text as="span" tone="tertiary" size="xs">
            Generated by {insight.provider} ({insight.provider_kind} v{insight.provider_version}).
          </Text>
        </div>
      )}
    </article>
  );
}

/** Compact variant for the dashboard, where space is scarce and the feed is a
 * preview rather than the destination. */
export function InsightCardCompact({ insight }: { insight: Insight }) {
  const Icon = INSIGHT_ICONS[insight.kind] ?? INSIGHT_ICONS.health_improvement;
  return (
    <div className="lf-insight lf-insight--compact" data-severity={insight.severity}>
      <span className="lf-insight-icon" aria-hidden="true">
        <Icon size={15} strokeWidth={1.9} />
      </span>
      <div>
        <p className="lf-insight-title">{insight.title}</p>
        <p className="lf-insight-body">{insight.body}</p>
      </div>
    </div>
  );
}
