# Generated by Django 5.2.16 on 2026-07-22 16:47

import apps.common.ids
"""Investment tracking: securities, holdings, lots, transactions, and prices.

Cost basis lives in the lots; market value is never stored. See the module
docstring in models.py for why.
"""

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_account_lifecycle_and_presentation'),
        ('ledger', '0002_financial_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('symbol', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('asset_class', models.CharField(choices=[('stock', 'Stocks'), ('etf', 'ETFs'), ('mutual_fund', 'Mutual funds'), ('bond', 'Bonds'), ('crypto', 'Crypto'), ('cash_equivalent', 'Cash investments'), ('real_estate', 'Real estate'), ('commodity', 'Commodities'), ('other', 'Other')], max_length=20)),
                ('sector', models.CharField(blank=True, default='', max_length=80)),
                ('currency', models.CharField(max_length=3)),
                ('exchange', models.CharField(blank=True, default='', max_length=32)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('quantity_precision', models.PositiveSmallIntegerField(default=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'securities',
                'indexes': [models.Index(fields=['tenant_id', 'asset_class'], name='security_class_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'symbol'), name='uniq_security_symbol')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='finance.financialaccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='investments.security')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('txn_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('interest', 'Interest'), ('fee', 'Fee'), ('split', 'Split')], max_length=12)),
                ('occurred_on', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('fee_minor', models.BigIntegerField(default=0)),
                ('realized_gain_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='investments.holding')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
                'indexes': [models.Index(fields=['tenant_id', 'holding', '-occurred_on'], name='invtxn_holding_idx'), models.Index(fields=['tenant_id', 'txn_type', '-occurred_on'], name='invtxn_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fee_minor__gte', 0)), name='invtxn_fee_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('acquired_on', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=28)),
                ('quantity_remaining', models.DecimalField(decimal_places=8, max_digits=28)),
                ('cost_minor', models.BigIntegerField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='investments.holding')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['acquired_on', 'id'],
                'indexes': [models.Index(fields=['tenant_id', 'holding', 'acquired_on'], name='lot_fifo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='lot_qty_positive'), models.CheckConstraint(condition=models.Q(('cost_minor__gte', 0)), name='lot_cost_non_negative'), models.CheckConstraint(condition=models.Q(('quantity_remaining__gte', 0)), name='lot_remaining_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('as_of', models.DateField()),
                ('price_minor', models.BigIntegerField()),
                ('source', models.CharField(default='manual', max_length=40)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='investments.security')),
            ],
            options={
                'ordering': ['-as_of'],
                'indexes': [models.Index(fields=['tenant_id', 'security', '-as_of'], name='quote_latest_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'security', 'as_of'), name='uniq_quote_security_date'), models.CheckConstraint(condition=models.Q(('price_minor__gte', 0)), name='quote_price_non_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['tenant_id', 'financial_account'], name='holding_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'financial_account', 'security'), name='uniq_holding_account_security'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='holding_qty_non_negative'),
        ),
    ]
