# Generated by Django 5.2.16 on 2026-08-05 10:22

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_rls_investment_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('interest', 'Interest'), ('fee', 'Fee'), ('split', 'Split'), ('redemption', 'Redemption')], max_length=12),
        ),
        migrations.CreateModel(
            name='RedemptionSchedule',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('on_date', models.DateField()),
                ('portion_bp', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='investments.security')),
            ],
            options={
                'ordering': ['on_date'],
                'indexes': [models.Index(fields=['tenant_id', 'security', 'on_date'], name='redemption_sched_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('portion_bp__gt', 0), ('portion_bp__lte', 10000)), name='redemption_portion_in_range')],
            },
        ),
        migrations.CreateModel(
            name='SecurityTerms',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('income_kind', models.CharField(choices=[('coupon', 'Fixed coupon'), ('variable', 'Variable rate'), ('declared', 'Declared periodically'), ('none', 'No regular income')], default='none', max_length=12)),
                ('face_value_minor', models.BigIntegerField(blank=True, null=True)),
                ('coupon_rate_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Twice a year'), ('annual', 'Annually')], max_length=12, null=True)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('matures_on', models.DateField(blank=True, null=True)),
                ('dividend_on_average_balance', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='investments.security')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'income_kind'], name='secterms_kind_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('face_value_minor__isnull', True), ('face_value_minor__gt', 0), _connector='OR'), name='secterms_face_positive'), models.CheckConstraint(condition=models.Q(('coupon_rate_bp__isnull', True), ('coupon_rate_bp__lte', 100000), _connector='OR'), name='secterms_rate_sane'), models.CheckConstraint(condition=models.Q(('matures_on__isnull', True), ('issued_on__isnull', True), ('matures_on__gte', models.F('issued_on')), _connector='OR'), name='secterms_matures_after_issue')],
            },
        ),
    ]
