# Generated by Django 5.2.16 on 2026-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_rls_terms_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityterms',
            name='payment_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Twice a year'), ('annual', 'Annually')], default='', max_length=12),
        ),
    ]
