# Generated by Django 5.2.16 on 2026-09-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_securityterms_payment_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='expense_ratio_bp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='security',
            constraint=models.CheckConstraint(condition=models.Q(('expense_ratio_bp__isnull', True), ('expense_ratio_bp__lte', 10000), _connector='OR'), name='security_ter_sane'),
        ),
    ]
