# Generated by Django 5.2.16 on 2026-08-05 06:55

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0005_financialaccount_overdraft_limit_minor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('counterparty', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('personal', 'Money I lent someone'), ('invoice', 'Unpaid invoice'), ('reimbursement', 'Owed a reimbursement'), ('deposit', 'Deposit held by someone else'), ('other', 'Something else')], default='personal', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('principal_minor', models.BigIntegerField()),
                ('lent_on', models.DateField()),
                ('due_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('settled', 'Settled'), ('written_off', 'Written off')], default='outstanding', max_length=12)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='finance.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('received_on', models.DateField()),
                ('amount_minor', models.BigIntegerField()),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='receivables.receivable')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_repayments', to='finance.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['tenant_id', 'status'], name='receivable_status_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['tenant_id', 'due_on'], name='receivable_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.CheckConstraint(condition=models.Q(('principal_minor__gt', 0)), name='receivable_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.CheckConstraint(condition=models.Q(('due_on__isnull', True), ('due_on__gte', models.F('lent_on')), _connector='OR'), name='receivable_due_after_lent'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['tenant_id', 'receivable', '-received_on'], name='repayment_hist_idx'),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='repayment_amount_positive'),
        ),
    ]
