# Generated by Django 5.2.16 on 2026-07-26 08:22

import apps.common.ids
import apps.platform_admin.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("actor_email", models.CharField(blank=True, default="", editable=False, max_length=254)),
                ("actor_role", models.CharField(blank=True, default="", editable=False, max_length=32)),
                ("action", models.CharField(max_length=64)),
                ("module", models.CharField(blank=True, default="", max_length=32)),
                ("target_type", models.CharField(blank=True, default="", max_length=64)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=400)),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="pa_audit_recent_idx"),
                    models.Index(fields=["actor_id", "-created_at"], name="pa_audit_actor_idx"),
                    models.Index(fields=["tenant_id", "-created_at"], name="pa_audit_tenant_idx"),
                    models.Index(fields=["module", "-created_at"], name="pa_audit_module_idx"),
                    models.Index(fields=["action", "-created_at"], name="pa_audit_action_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlatformStaff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("platform_owner", "Platform Owner"),
                            ("platform_administrator", "Platform Administrator"),
                            ("billing_administrator", "Billing Administrator"),
                            ("finance", "Finance"),
                            ("customer_success", "Customer Success"),
                            ("technical_support", "Technical Support"),
                            ("read_only_auditor", "Read Only Auditor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("extra_capabilities", models.JSONField(blank=True, default=list)),
                ("denied_capabilities", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("allowed_ips", models.JSONField(blank=True, default=list)),
                ("require_mfa", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_grants_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "platform staff member",
                "verbose_name_plural": "platform staff",
            },
        ),
        migrations.CreateModel(
            name="ImpersonationGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("subject_user_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("read_only", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=apps.platform_admin.models._default_impersonation_expiry),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impersonations_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonations",
                        to="platform_admin.platformstaff",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("surface", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=80)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("is_shared", models.BooleanField(default=False)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to="platform_admin.platformstaff",
                    ),
                ),
            ],
            options={
                "ordering": ["surface", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlatformNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(max_length=40)),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("critical", "Critical")],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, default="", max_length=600)),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("subject_type", models.CharField(blank=True, default="", max_length=40)),
                ("subject_id", models.UUIDField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("dedupe_key", models.CharField(blank=True, default="", max_length=200)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_channels", models.JSONField(blank=True, default=list)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_notifications_acked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="pa_notif_recent_idx"),
                    models.Index(
                        condition=models.Q(("acknowledged_at__isnull", True)),
                        fields=["severity", "-created_at"],
                        name="pa_notif_open_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key", ""), _negated=True),
                        fields=("dedupe_key",),
                        name="uniq_platform_notification_dedupe",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="platformstaff",
            index=models.Index(fields=["is_active", "role"], name="platform_ad_is_acti_5750cc_idx"),
        ),
        migrations.AddIndex(
            model_name="impersonationgrant",
            index=models.Index(fields=["status", "-created_at"], name="platform_ad_status_e82051_idx"),
        ),
        migrations.AddIndex(
            model_name="impersonationgrant",
            index=models.Index(fields=["staff", "-created_at"], name="platform_ad_staff_i_575182_idx"),
        ),
        migrations.AddIndex(
            model_name="savedview",
            index=models.Index(fields=["surface", "is_shared"], name="platform_ad_surface_757f61_idx"),
        ),
        migrations.AddConstraint(
            model_name="savedview",
            constraint=models.UniqueConstraint(
                fields=("staff", "surface", "name"), name="uniq_saved_view_name"
            ),
        ),
    ]
