# Generated by Django 5.2.16 on 2026-07-26 08:35

import apps.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0002_audit_immutability"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantUsageSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("account_count", models.PositiveIntegerField(default=0)),
                ("transaction_count", models.PositiveIntegerField(default=0)),
                ("attachment_count", models.PositiveIntegerField(default=0)),
                ("storage_bytes", models.BigIntegerField(default=0)),
                ("api_calls", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [models.Index(fields=["tenant_id", "-captured_at"], name="pa_usage_latest_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "captured_at"), name="uniq_usage_snapshot_per_capture"
                    )
                ],
            },
        ),
    ]
