# Generated by Django 5.2.16 on 2026-07-19 20:08

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(choices=[("card", "Card"), ("mpesa", "M-PESA")], max_length=16)),
                ("is_default", models.BooleanField(default=False)),
                ("brand", models.CharField(blank=True, default="", max_length=32)),
                ("last4", models.CharField(blank=True, default="", max_length=4)),
                ("exp_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("exp_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("phone_masked", models.CharField(blank=True, default="", max_length=20)),
                ("provider", models.CharField(max_length=32)),
                ("provider_ref", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "is_default"], name="billing_pay_tenant__2e02d0_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("plus", "Plus"),
                            ("family", "Family"),
                            ("business", "Business"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("price_minor", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("max_members", models.PositiveSmallIntegerField(default=1)),
                ("max_accounts", models.PositiveSmallIntegerField(default=3)),
                ("ai_insights", models.BooleanField(default=False)),
                ("features", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "price_minor"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tier", "interval", "currency"), name="uniq_plan_tier_interval_currency"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="incomplete",
                        max_length=16,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, default="", max_length=32)),
                ("provider_ref", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("amount_minor", models.PositiveIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("provider_ref", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("failure_reason", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=32)),
                ("event_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["provider", "event_type"], name="billing_web_provide_47f030_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"), name="uniq_webhook_provider_event"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["provider", "provider_ref"], name="billing_sub_provide_b6febd_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="billing_sub_status_948046_idx"),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(fields=("tenant_id",), name="uniq_subscription_per_tenant"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["tenant_id", "status"], name="billing_pay_tenant__9b948c_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["provider", "provider_ref"], name="billing_pay_provide_357f14_idx"),
        ),
    ]
