# Generated by Django 5.2.16 on 2026-07-26 08:22

import apps.common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceSequence",
            fields=[
                ("year", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "invoice sequence",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage off"),
                            ("fixed", "Fixed amount off"),
                            ("free_months", "Free months"),
                            ("trial_extension", "Trial extension"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                (
                    "duration",
                    models.CharField(
                        choices=[("once", "Once"), ("repeating", "Repeating"), ("forever", "Forever")],
                        default="once",
                        max_length=12,
                    ),
                ),
                ("duration_in_months", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("allowed_countries", models.JSONField(blank=True, default=list)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                ("max_redemptions_per_tenant", models.PositiveSmallIntegerField(default=1)),
                ("redemption_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "applies_to_plans",
                    models.ManyToManyField(blank=True, related_name="coupons", to="billing.plan"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupons_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("amount_minor", models.PositiveIntegerField()),
                ("remaining_minor", models.PositiveIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("goodwill", "Goodwill"),
                            ("promotional", "Promotional"),
                            ("adjustment", "Billing adjustment"),
                            ("refund_offset", "Refund offset"),
                        ],
                        default="goodwill",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credits_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DunningCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("recovered", "Recovered"),
                            ("suspended", "Suspended"),
                            ("abandoned", "Abandoned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("amount_minor", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("opened_at", models.DateTimeField()),
                ("grace_ends_at", models.DateTimeField(blank=True, null=True)),
                ("suspend_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("attempts_made", models.PositiveSmallIntegerField(default=0)),
                ("last_failure_reason", models.CharField(blank=True, default="", max_length=255)),
                ("resolution_note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dunning_cases",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="DunningAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("retry", "Payment retry"),
                            ("reminder_email", "Reminder email"),
                            ("reminder_sms", "Reminder SMS"),
                            ("suspend", "Suspension"),
                            ("abandon", "Abandonment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dunning_attempts",
                        to="billing.payment",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="billing.dunningcase",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="DunningPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("retry_offsets_days", models.JSONField(blank=True, default=list)),
                ("reminder_offsets_days", models.JSONField(blank=True, default=list)),
                ("grace_period_days", models.PositiveSmallIntegerField(default=14)),
                ("suspend_after_days", models.PositiveSmallIntegerField(default=21)),
                ("abandon_after_days", models.PositiveSmallIntegerField(default=45)),
                ("send_email", models.BooleanField(default=True)),
                ("send_sms", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applies_to_plans",
                    models.ManyToManyField(blank=True, related_name="dunning_policies", to="billing.plan"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="dunningcase",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="billing.dunningpolicy",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("subtotal_minor", models.PositiveIntegerField(default=0)),
                ("discount_minor", models.PositiveIntegerField(default=0)),
                ("credit_minor", models.PositiveIntegerField(default=0)),
                ("tax_minor", models.PositiveIntegerField(default=0)),
                ("total_minor", models.PositiveIntegerField(default=0)),
                ("amount_paid_minor", models.PositiveIntegerField(default=0)),
                ("tax_rate_bps", models.PositiveIntegerField(default=0)),
                ("tax_label", models.CharField(blank=True, default="", max_length=40)),
                ("billing_name", models.CharField(blank=True, default="", max_length=200)),
                ("billing_email", models.EmailField(blank=True, default="", max_length=254)),
                ("billing_country", models.CharField(blank=True, default="", max_length=2)),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.coupon",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="dunningcase",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dunning_cases",
                to="billing.invoice",
            ),
        ),
        migrations.CreateModel(
            name="CreditApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_minor", models.PositiveIntegerField()),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="billing.credit",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_applications",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("discount_minor", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("periods_applied", models.PositiveSmallIntegerField(default=0)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="billing.coupon",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redemptions",
                        to="billing.subscription",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redemptions",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_amount_minor", models.PositiveIntegerField(default=0)),
                ("amount_minor", models.PositiveIntegerField(default=0)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("amount_minor", models.PositiveIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True, default="")),
                ("provider", models.CharField(blank=True, default="", max_length=32)),
                ("provider_ref", models.CharField(blank=True, default="", max_length=255)),
                ("failure_reason", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="billing.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="billing.payment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["is_active", "-created_at"], name="billing_cou_is_acti_d1abed_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["kind"], name="billing_cou_kind_7fbe92_idx"),
        ),
        migrations.AddIndex(
            model_name="credit",
            index=models.Index(fields=["tenant_id", "-created_at"], name="billing_cre_tenant__850a16_idx"),
        ),
        migrations.AddIndex(
            model_name="credit",
            index=models.Index(
                condition=models.Q(("remaining_minor__gt", 0), ("voided_at__isnull", True)),
                fields=["tenant_id", "currency", "created_at"],
                name="billing_credit_live_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dunningattempt",
            index=models.Index(
                condition=models.Q(("outcome", "scheduled")), fields=["scheduled_for"], name="dunning_due_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dunningattempt",
            constraint=models.UniqueConstraint(
                fields=("case", "kind", "sequence"), name="uniq_dunning_attempt_step"
            ),
        ),
        migrations.AddConstraint(
            model_name="dunningpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="uniq_default_dunning_policy",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["tenant_id", "-issue_date"], name="billing_inv_tenant__23130f_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status", "due_date"], name="billing_inv_status_996e80_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["-created_at"], name="billing_inv_created_42771e_idx"),
        ),
        migrations.AddIndex(
            model_name="dunningcase",
            index=models.Index(fields=["status", "-opened_at"], name="billing_dun_status_c436ff_idx"),
        ),
        migrations.AddIndex(
            model_name="dunningcase",
            index=models.Index(fields=["tenant_id", "-opened_at"], name="billing_dun_tenant__4ad6e8_idx"),
        ),
        migrations.AddConstraint(
            model_name="dunningcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("subscription",),
                name="uniq_open_dunning_case_per_subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditapplication",
            constraint=models.UniqueConstraint(fields=("credit", "invoice"), name="uniq_credit_per_invoice"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["coupon", "-created_at"], name="billing_cou_coupon__5d15d6_idx"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["tenant_id", "-created_at"], name="billing_cou_tenant__4a344c_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["tenant_id", "-created_at"], name="billing_ref_tenant__83fec6_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["status", "-created_at"], name="billing_ref_status_68ba22_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["provider", "provider_ref"], name="billing_ref_provide_841118_idx"),
        ),
    ]
