# Generated by Django 5.2.16 on 2026-07-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_invoicesequence_coupon_credit_dunningcase_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dunningcase",
            name="uniq_open_dunning_case_per_subscription",
        ),
        migrations.AddConstraint(
            model_name="dunningcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["open", "suspended"])),
                fields=("subscription",),
                name="uniq_open_dunning_case_per_subscription",
            ),
        ),
    ]
