# Generated by Django 5.2.16 on 2026-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_live_dunning_case_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('free', 'Free'), ('plus', 'Plus'), ('family', 'Family'), ('business', 'Business')], max_length=16),
        ),
    ]
