# Generated by Django 5.2.16 on 2026-09-21 14:01

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_rls_asset_tables'),
        ('finance', '0006_bill_recurring_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('life', 'Life'), ('health', 'Health'), ('motor', 'Motor'), ('home', 'Home'), ('liability', 'Liability'), ('other', 'Something else')], default='other', max_length=16)),
                ('insurer', models.CharField(blank=True, default='', max_length=120)),
                ('currency', models.CharField(max_length=3)),
                ('coverage_minor', models.BigIntegerField(blank=True, null=True)),
                ('deductible_minor', models.BigIntegerField(blank=True, null=True)),
                ('premium_minor', models.BigIntegerField()),
                ('premium_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annually')], default='annual', max_length=12)),
                ('renews_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policy', to='finance.bill')),
                ('covers_account', models.ForeignKey(blank=True, help_text='A loan this policy is written against — a motor policy on a car loan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policies', to='finance.financialaccount')),
                ('covers_asset', models.ForeignKey(blank=True, help_text='The house, car or other asset this policy covers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policies', to='assets.asset')),
                ('recurring_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policy', to='finance.recurringtransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='insurance_active_idx'), models.Index(fields=['tenant_id', 'kind'], name='insurance_kind_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('premium_minor__gt', 0)), name='insurance_premium_positive'), models.CheckConstraint(condition=models.Q(('coverage_minor__isnull', True), ('coverage_minor__gte', 0), _connector='OR'), name='insurance_coverage_non_negative'), models.CheckConstraint(condition=models.Q(('deductible_minor__isnull', True), ('deductible_minor__gte', 0), _connector='OR'), name='insurance_deductible_non_negative'), models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('renews_on__isnull', True), ('ends_on__gte', models.F('renews_on')), _connector='OR'), name='insurance_ends_after_renewal')],
            },
        ),
    ]
