# Generated by Django 5.2.16 on 2026-07-18 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="invited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["is_active"], name="tenancy_ten_is_acti_108262_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["type"], name="tenancy_ten_type_dd6443_idx"),
        ),
        migrations.AddField(
            model_name="membership",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="tenancy.tenant"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="tenancy.tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["user", "tenant"], name="tenancy_mem_user_id_889db6_idx"),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(fields=("tenant", "user"), name="uniq_tenant_user"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["tenant", "status"], name="tenancy_inv_tenant__f310a5_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["email", "status"], name="tenancy_inv_email_0a194d_idx"),
        ),
    ]
