# Generated by Django 5.2.16 on 2026-07-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
