# Generated by Django 5.2.16 on 2026-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_tenant_ai_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
