# Generated by Django 5.2.16 on 2026-08-04 10:28

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_tenant_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAISettings',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('base_url', models.URLField(blank=True, default='')),
                ('encrypted_api_key', models.TextField(blank=True, default='')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'workspace AI settings',
                'verbose_name_plural': 'workspace AI settings',
            },
        ),
    ]
