# Generated by Django 5.2.16 on 2026-08-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_tenantaisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='base_currency_chosen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
