# Generated by Django 5.2.16 on 2026-08-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_tenant_base_currency_chosen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='block_overdrafts',
            field=models.BooleanField(default=True),
        ),
    ]
