# Generated by Django 5.2.16 on 2026-07-18 05:03

import apps.common.ids
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(blank=True, default="", max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense"), ("transfer", "Transfer")],
                        max_length=10,
                    ),
                ),
                ("path", models.CharField(db_index=True, default="", max_length=255)),
                ("depth", models.PositiveSmallIntegerField(default=0)),
                ("is_system", models.BooleanField(default=False)),
                ("color", models.CharField(blank=True, default="", max_length=9)),
                ("icon", models.CharField(blank=True, default="", max_length=40)),
                (
                    "ledger_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category",
                        to="ledger.account",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="finance.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                ("swift_bic", models.CharField(blank=True, default="", max_length=11)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("aggregator", models.CharField(blank=True, default="", max_length=40)),
                ("external_id", models.CharField(blank=True, default="", max_length=128)),
            ],
            options={
                "indexes": [models.Index(fields=["name"], name="finance_ins_name_18f698_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("aggregator", "external_id"),
                        name="uniq_institution_external",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("credit_card", "Credit card"),
                            ("loan", "Loan"),
                            ("cash", "Cash"),
                            ("investment", "Investment"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("mask", models.CharField(blank=True, default="", max_length=4)),
                ("is_active", models.BooleanField(default=True)),
                ("external_id", models.CharField(blank=True, default="", max_length=128)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ledger_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_account",
                        to="ledger.account",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="finance.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=160)),
                ("normalized_name", models.CharField(db_index=True, max_length=160)),
                (
                    "default_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payees",
                        to="finance.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "txn_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense"), ("transfer", "Transfer")],
                        max_length=10,
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("memo", models.CharField(blank=True, default="", max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("interval", models.PositiveSmallIntegerField(default=1)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("max_occurrences", models.PositiveIntegerField(blank=True, null=True)),
                ("next_run_on", models.DateField(db_index=True)),
                ("occurrences_created", models.PositiveIntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_transactions",
                        to="finance.category",
                    ),
                ),
                (
                    "counter_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_recurring_transactions",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "financial_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_transactions",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_transactions",
                        to="finance.payee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=40)),
                ("color", models.CharField(blank=True, default="", max_length=9)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant_id", "name"),
                        name="uniq_tag_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("occurred_at", models.DateTimeField()),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("posted", "Posted"),
                            ("reconciled", "Reconciled"),
                            ("void", "Void"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("imported", "Imported"),
                            ("rule", "Rule"),
                            ("recurring", "Recurring"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("transfer_group", models.UUIDField(blank=True, db_index=True, null=True)),
                ("memo", models.CharField(blank=True, default="", max_length=255)),
                ("external_id", models.CharField(blank=True, default="", max_length=128)),
                ("needs_review", models.BooleanField(default=False)),
                ("review_reason", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.category",
                    ),
                ),
                (
                    "counter_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "financial_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.payee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("storage_key", models.CharField(max_length=512)),
                ("content_type", models.CharField(max_length=100)),
                ("byte_size", models.BigIntegerField()),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("uploaded", "Uploaded")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="finance.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="finance.tag",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="finance.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.ManyToManyField(
                related_name="transactions", through="finance.TransactionTag", to="finance.tag"
            ),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=120)),
                ("icon", models.CharField(blank=True, default="", max_length=40)),
                ("color", models.CharField(blank=True, default="", max_length=9)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant_id", "name"),
                        name="uniq_wallet_name",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="finance.wallet",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["tenant_id", "kind"], name="finance_cat_tenant__e640ec_idx"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "parent", "name"),
                name="uniq_category_name_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), models.Q(("slug", ""), _negated=True)),
                fields=("tenant_id", "slug"),
                name="uniq_category_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="payee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "normalized_name"),
                name="uniq_payee_normalized",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(fields=["tenant_id", "is_active", "next_run_on"], name="recurring_due_idx"),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_minor__gt", 0)), name="recurring_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval__gte", 1)), name="recurring_interval_min"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["tenant_id", "transaction"], name="finance_att_tenant__17b086_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["tenant_id", "status"], name="finance_att_tenant__22b4e1_idx"),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_size__gt", 0)), name="attachment_size_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="transactiontag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("transaction", "tag"),
                name="uniq_transaction_tag",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["tenant_id", "financial_account", "-occurred_at"],
                name="finance_tra_tenant__77a8df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["tenant_id", "category", "-occurred_at"], name="finance_tra_tenant__a2bec0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["tenant_id", "-occurred_at", "-id"], name="txn_list_cursor_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                condition=models.Q(("transfer_group__isnull", True)),
                fields=["tenant_id", "-occurred_at"],
                name="txn_non_transfer_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["tenant_id", "status"],
                name="txn_status_pending",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                condition=models.Q(("needs_review", True)),
                fields=["tenant_id", "-occurred_at"],
                name="txn_needs_review",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=django.contrib.postgres.indexes.BrinIndex(fields=["occurred_at"], name="txn_occurred_brin"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=django.contrib.postgres.indexes.GinIndex(fields=["metadata"], name="txn_metadata_gin"),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("financial_account", "external_id"),
                name="uniq_txn_external",
            ),
        ),
        migrations.AddIndex(
            model_name="financialaccount",
            index=models.Index(
                fields=["tenant_id", "account_type", "is_active"], name="finance_fin_tenant__aacb00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialaccount",
            index=models.Index(fields=["tenant_id", "wallet"], name="finance_fin_tenant__79bd02_idx"),
        ),
        migrations.AddIndex(
            model_name="financialaccount",
            index=django.contrib.postgres.indexes.GinIndex(fields=["metadata"], name="faccount_metadata_gin"),
        ),
        migrations.AddConstraint(
            model_name="financialaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "name"),
                name="uniq_faccount_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("external_id",),
                name="uniq_faccount_external",
            ),
        ),
    ]
