# Generated by Django 5.2.16 on 2026-07-22 06:34

"""Account lifecycle, presentation, and reporting-inclusion fields.

All additive with safe defaults, so this is a zero-downtime deploy: existing
rows become visible, unarchived, included accounts — exactly their behaviour
before the change.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_split_group_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='include_in_budgets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='include_in_net_worth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
