# Generated by Django 5.2.16 on 2026-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_account_lifecycle_and_presentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
