# Generated by Django 5.2.16 on 2026-08-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_reconciled_at'),
        ('ledger', '0002_financial_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='overdraft_limit_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(('overdraft_limit_minor__gte', 0)), name='faccount_overdraft_limit_non_negative'),
        ),
    ]
