# Generated by Django 5.2.16 on 2026-09-11 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financialaccount_overdraft_limit_minor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='recurring_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='finance.recurringtransaction'),
        ),
    ]
