/**
 * The application preview on the landing page.
 *
 * This is a real screenshot of the Overview screen, captured from the running
 * app by `scripts/capture_preview.py` against the seeded demo tenant.
 *
 * It replaced a token-built abstraction that showed only the *shape* of the
 * interface. The abstraction was chosen to dodge three genuine problems, all
 * of which the capture script answers directly:
 *
 * * a screenshot goes stale — so it is generated by a script, and
 *   `capture_preview.py --check` fails when the dashboard drifts away from it;
 * * a screenshot cannot follow the visitor's colour scheme — so both themes
 *   are captured and swapped below with the same CSS the rest of the site uses;
 * * a screenshot with figures either shows someone's real data or invents data
 *   presented as real — so the source is the demo tenant the repo already
 *   ships, and the alt text says as much in those words.
 *
 * What the abstraction could never do is show the thing the page is actually
 * claiming: that the screens are legible and the numbers are laid out to be
 * checked. Grey bars cannot make that argument.
 */
const ALT =
  "The LedgerFlow overview screen, showing net worth of KES 39,058.70 broken " +
  "into assets and liabilities, a six-month trend, and a financial health " +
  "score of 72. Figures are from the demo workspace, not a real customer.";

export function AppPreview() {
  return (
    <div className="lf-preview">
      <div className="lf-preview-chrome" aria-hidden="true">
        <span />
        <span />
        <span />
      </div>
      {/* Two elements rather than <picture>, because a <picture> can only
          respond to `prefers-color-scheme` — it cannot see the `data-theme`
          attribute the theme toggle sets, so a visitor who overrode their
          system theme would get the wrong screenshot. */}
      <img
        className="lf-preview-shot lf-preview-shot--light"
        src="/preview-dashboard-light.webp"
        alt={ALT}
        width={948}
        height={412}
        loading="lazy"
        decoding="async"
      />
      <img
        className="lf-preview-shot lf-preview-shot--dark"
        src="/preview-dashboard-dark.webp"
        alt=""
        aria-hidden="true"
        width={948}
        height={412}
        loading="lazy"
        decoding="async"
      />
    </div>
  );
}
