# Generated by Django 5.2.16 on 2026-08-04 19:19

import apps.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('monthly_spend', 'Monthly spending'), ('monthly_income', 'Monthly income'), ('closing_liquid', 'Cash at month end')], max_length=24)),
                ('period', models.DateField()),
                ('made_on', models.DateField()),
                ('predicted_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('months_observed', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.CharField(default='none', max_length=12)),
                ('actual_minor', models.BigIntegerField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['tenant_id', 'kind', 'period'], name='forecast_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'kind', 'period'), name='uniq_forecast_period')],
            },
        ),
    ]
