# Generated by Django 5.2.16 on 2026-07-23 08:11

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_account_lifecycle_and_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('pending_upload', 'Awaiting upload'), ('uploaded', 'Uploaded'), ('processing', 'Reading receipt'), ('parsed', 'Ready for review'), ('unreadable', "Couldn't read this one"), ('failed', 'Processing failed'), ('linked', 'Added to your transactions'), ('discarded', 'Discarded')], default='pending_upload', max_length=16)),
                ('storage_key', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_fields', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('confirmed_merchant', models.CharField(blank=True, default='', max_length=160)),
                ('confirmed_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('confirmed_occurred_on', models.DateField(blank=True, null=True)),
                ('confirmed_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.category')),
                ('financial_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='finance.financialaccount')),
                ('linked_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='finance.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='receipt_status_idx'), models.Index(fields=['tenant_id', '-created_at'], name='receipt_recent_idx')],
            },
        ),
    ]
