# Generated by Django 5.2.16 on 2026-07-18 05:03

import apps.common.ids
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("action", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.UUIDField()),
                ("changes", models.JSONField(default=dict)),
                ("context", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "target_type", "target_id"],
                        name="common_audi_tenant__c7f2d4_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "actor_id", "created_at"], name="common_audi_tenant__35e33c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("aggregate_type", models.CharField(max_length=64)),
                ("aggregate_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=128)),
                ("payload", models.JSONField(default=dict)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["published_at", "id"], name="common_outb_publish_cb526e_idx")
                ],
            },
        ),
    ]
