# Generated by Django 5.2.16 on 2026-07-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="target_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
