# Generated by Django 5.2.16 on 2026-08-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_receipt_scanner',
            field=models.BooleanField(default=False),
        ),
    ]
