# Generated by Django 5.2.16 on 2026-07-18 05:03

import apps.common.ids
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("income", "Income"),
                            ("expense", "Expense"),
                        ],
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("is_system", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "kind"], name="ledger_acco_tenant__f436d3_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "name", "kind"), name="uniq_account_name_kind"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency__regex", "^[A-Z]{3}$")), name="account_currency_iso"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("balance_minor", models.BigIntegerField(default=0)),
                ("currency", models.CharField(max_length=3)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to="ledger.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("occurred_at", models.DateTimeField()),
                ("currency", models.CharField(max_length=3)),
                ("memo", models.CharField(blank=True, default="", max_length=255)),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="ledger.journalentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "direction",
                    models.CharField(choices=[("debit", "Debit"), ("credit", "Credit")], max_length=6),
                ),
                ("amount_minor", models.BigIntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="ledger.account"
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="ledger.journalentry",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["occurred_at"], name="journalentry_occurred_brin"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "idempotency_key"), name="uniq_entry_idempotency"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerline",
            index=models.Index(fields=["tenant_id", "account", "id"], name="ledger_ledg_tenant__d5e09e_idx"),
        ),
        migrations.AddConstraint(
            model_name="ledgerline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_minor__gt", 0)), name="line_amount_positive"
            ),
        ),
    ]
