# Generated by Django 5.2.16 on 2026-08-05 11:40

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0005_financialaccount_overdraft_limit_minor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('property', 'Property'), ('land', 'Land'), ('vehicle', 'Vehicle'), ('valuable', 'Valuables'), ('business', 'Business stake'), ('other', 'Something else')], default='other', max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('acquisition_cost_minor', models.BigIntegerField(blank=True, null=True)),
                ('include_in_net_worth', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('secured_by_debt', models.ForeignKey(blank=True, help_text='The loan or mortgage secured on this asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secured_assets', to='finance.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('as_of', models.DateField()),
                ('value_minor', models.BigIntegerField()),
                ('source', models.CharField(choices=[('purchase', 'What it cost'), ('owner', 'My own estimate'), ('professional', 'Professional valuation'), ('market', 'Market listing or index')], default='owner', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='assets.asset')),
            ],
            options={
                'ordering': ['-as_of'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant_id', 'kind'], name='asset_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant_id', 'include_in_net_worth'], name='asset_networth_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('acquisition_cost_minor__isnull', True), ('acquisition_cost_minor__gte', 0), _connector='OR'), name='asset_cost_non_negative'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['tenant_id', 'asset', '-as_of'], name='valuation_hist_idx'),
        ),
        migrations.AddConstraint(
            model_name='valuation',
            constraint=models.CheckConstraint(condition=models.Q(('value_minor__gte', 0)), name='valuation_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='valuation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'as_of'), name='uniq_valuation_per_day'),
        ),
    ]
