from django.urls import path

from .views import (
    AccountDetailView,
    AccountStatementView,
    AccountUnarchiveView,
    AccountView,
    AttachmentConfirmView,
    AttachmentDownloadView,
    AttachmentUploadRequestView,
    AttachmentUploadView,
    BillDetailView,
    BillPayView,
    BillView,
    CashflowCalendarView,
    CashflowDayView,
    CashflowStatementView,
    CashFlowView,
    CategoryBreakdownView,
    CategoryDetailView,
    CategoryTrendView,
    CategoryView,
    NetWorthBaseView,
    NetWorthView,
    PayeeView,
    QuickAddView,
    RecentMerchantsView,
    ReconcileMarkView,
    ReconciliationView,
    RecurringDetailView,
    RecurringView,
    TagDetailView,
    TagView,
    TransactionAttachmentsView,
    TransactionBulkView,
    TransactionDetailView,
    TransactionExportView,
    TransactionImportView,
    TransactionReviewCountView,
    TransactionSplitView,
    TransactionTagsView,
    TransactionView,
    TransactionVoidView,
    TransferView,
    WalletAccountAssignmentView,
    WalletBalanceView,
    WalletView,
)

urlpatterns = [
    path("cashflow-calendar/", CashflowCalendarView.as_view(), name="finance-cashflow-calendar"),
    path(
        "cashflow-calendar/<slug:day>/",
        CashflowDayView.as_view(),
        name="finance-cashflow-day",
    ),
    path("quick-add/", QuickAddView.as_view(), name="finance-quick-add"),
    path("quick-add/recent-merchants/", RecentMerchantsView.as_view(), name="finance-recent-merchants"),
    path("accounts/", AccountView.as_view(), name="finance-accounts"),
    path("accounts/<uuid:account_id>/", AccountDetailView.as_view(), name="finance-account-detail"),
    path(
        "accounts/<uuid:account_id>/unarchive/",
        AccountUnarchiveView.as_view(),
        name="finance-account-unarchive",
    ),
    path(
        "accounts/<uuid:account_id>/statement/",
        AccountStatementView.as_view(),
        name="finance-account-statement",
    ),
    path("wallets/", WalletView.as_view(), name="finance-wallets"),
    path("wallets/<uuid:wallet_id>/", WalletBalanceView.as_view(), name="finance-wallet-detail"),
    path(
        "wallets/assign-account/", WalletAccountAssignmentView.as_view(), name="finance-wallet-assign-account"
    ),
    path("categories/", CategoryView.as_view(), name="finance-categories"),
    path("categories/<uuid:category_id>/", CategoryDetailView.as_view(), name="finance-category-detail"),
    path("payees/", PayeeView.as_view(), name="finance-payees"),
    path(
        "accounts/<uuid:account_id>/reconciliation/",
        ReconciliationView.as_view(),
        name="finance-account-reconciliation",
    ),
    path(
        "transactions/reconcile/",
        ReconcileMarkView.as_view(),
        name="finance-transactions-reconcile",
    ),
    path("tags/", TagView.as_view(), name="finance-tags"),
    path("tags/<uuid:tag_id>/", TagDetailView.as_view(), name="finance-tag-detail"),
    path("transactions/", TransactionView.as_view(), name="finance-transactions"),
    path(
        "transactions/review-count/",
        TransactionReviewCountView.as_view(),
        name="finance-transaction-review-count",
    ),
    path("transactions/export/", TransactionExportView.as_view(), name="finance-transaction-export"),
    path("transactions/import/", TransactionImportView.as_view(), name="finance-transaction-import"),
    path("transactions/bulk/", TransactionBulkView.as_view(), name="finance-transaction-bulk"),
    path("transactions/<uuid:txn_id>/", TransactionDetailView.as_view(), name="finance-transaction-detail"),
    path("transactions/<uuid:txn_id>/void/", TransactionVoidView.as_view(), name="finance-transaction-void"),
    path("transactions/<uuid:txn_id>/tags/", TransactionTagsView.as_view(), name="finance-transaction-tags"),
    path(
        "transactions/<uuid:txn_id>/attachments/",
        TransactionAttachmentsView.as_view(),
        name="finance-transaction-attachments",
    ),
    path(
        "transactions/<uuid:txn_id>/attachments/request-upload/",
        AttachmentUploadRequestView.as_view(),
        name="finance-attachment-request-upload",
    ),
    path(
        "attachments/<uuid:attachment_id>/confirm/",
        AttachmentConfirmView.as_view(),
        name="finance-attachment-confirm",
    ),
    path(
        "attachments/<uuid:attachment_id>/upload/",
        AttachmentUploadView.as_view(),
        name="finance-attachment-upload",
    ),
    path(
        "attachments/<uuid:attachment_id>/download/",
        AttachmentDownloadView.as_view(),
        name="finance-attachment-download",
    ),
    path(
        "transactions/<uuid:txn_id>/split/",
        TransactionSplitView.as_view(),
        name="finance-transaction-split",
    ),
    path("transfers/", TransferView.as_view(), name="finance-transfers"),
    path("recurring/", RecurringView.as_view(), name="finance-recurring"),
    path("recurring/<uuid:rec_id>/", RecurringDetailView.as_view(), name="finance-recurring-detail"),
    path("bills/", BillView.as_view(), name="finance-bills"),
    path("bills/<uuid:bill_id>/", BillDetailView.as_view(), name="finance-bill-detail"),
    path("bills/<uuid:bill_id>/pay/", BillPayView.as_view(), name="finance-bill-pay"),
    path("net-worth/", NetWorthView.as_view(), name="finance-net-worth"),
    path("net-worth/base/", NetWorthBaseView.as_view(), name="finance-net-worth-base"),
    path("cash-flow/", CashFlowView.as_view(), name="finance-cash-flow"),
    path("cashflow-statement/", CashflowStatementView.as_view(), name="finance-cashflow-statement"),
    path("category-breakdown/", CategoryBreakdownView.as_view(), name="finance-category-breakdown"),
    path("category-trend/", CategoryTrendView.as_view(), name="finance-category-trend"),
]
