# Generated by Django 5.2.16 on 2026-07-18 05:03

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=100)),
                ("conditions", models.JSONField(default=dict)),
                ("actions", models.JSONField(default=list)),
                ("stop_processing", models.BooleanField(default=False)),
                ("match_count", models.PositiveIntegerField(default=0)),
                ("last_matched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "is_active", "priority"], name="intelligenc_tenant__57aa00_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CategorizationSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("provider_kind", models.CharField(max_length=16)),
                ("provider_version", models.CharField(max_length=16)),
                ("rationale", models.CharField(blank=True, default="", max_length=255)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "suggested_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finance.category",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_suggestions",
                        to="finance.transaction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "status"], name="intelligenc_tenant__37b6d8_idx"),
                    models.Index(fields=["tenant_id", "transaction"], name="intelligenc_tenant__c52aa0_idx"),
                ],
            },
        ),
    ]
