# Generated by Django 5.2.16 on 2026-07-22 15:13

import apps.common.ids
import django.db.models.deletion
"""Stored insights and periodic briefings for the AI financial coach.

Additive only. RLS policies for both tables are installed by 0003.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_lifecycle_and_presentation'),
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('spending_anomaly', 'Spending anomaly'), ('overspending', 'Overspending warning'), ('budget_recommendation', 'Budget recommendation'), ('savings_opportunity', 'Savings opportunity'), ('duplicate_transaction', 'Possible duplicate'), ('large_purchase', 'Large purchase'), ('merchant_change', 'Merchant price change'), ('salary_change', 'Income change'), ('cashflow_risk', 'Cash flow risk'), ('subscription_review', 'Subscription review'), ('goal_recommendation', 'Goal recommendation'), ('debt_recommendation', 'Debt recommendation'), ('health_improvement', 'Financial health')], max_length=32)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('opportunity', 'Opportunity'), ('info', 'Informational')], max_length=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('bookmarked', 'Bookmarked'), ('dismissed', 'Dismissed'), ('acted', 'Acted on')], default='new', max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('rationale', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('action', models.JSONField(blank=True, default=dict)),
                ('priority_score', models.PositiveSmallIntegerField(default=0)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(max_length=64)),
                ('provider_kind', models.CharField(max_length=16)),
                ('provider_version', models.CharField(max_length=16)),
                ('last_detected_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('related_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.financialaccount')),
                ('related_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.category')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.transaction')),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('period', models.CharField(choices=[('daily', 'Daily briefing'), ('weekly', 'Weekly review'), ('monthly', 'Monthly review')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('headline', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(max_length=64)),
                ('provider_kind', models.CharField(max_length=16)),
                ('provider_version', models.CharField(max_length=16)),
                ('insights', models.ManyToManyField(blank=True, related_name='briefings', to='intelligence.insight')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['tenant_id', 'status', '-priority_score'], name='insight_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['tenant_id', 'kind'], name='insight_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['tenant_id', 'expires_on'], name='insight_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='insight',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'dedupe_key'), name='uniq_insight_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='insight',
            constraint=models.CheckConstraint(condition=models.Q(('priority_score__lte', 100)), name='insight_score_max'),
        ),
        migrations.AddIndex(
            model_name='briefing',
            index=models.Index(fields=['tenant_id', 'period', '-period_start'], name='briefing_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='briefing',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'period', 'period_start'), name='uniq_briefing_period'),
        ),
    ]
