# Generated by Django 5.2.16 on 2026-07-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_rls_coach_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='kind',
            field=models.CharField(choices=[('spending_anomaly', 'Spending anomaly'), ('overspending', 'Overspending warning'), ('budget_recommendation', 'Budget recommendation'), ('savings_opportunity', 'Savings opportunity'), ('duplicate_transaction', 'Possible duplicate'), ('large_purchase', 'Large purchase'), ('merchant_change', 'Merchant price change'), ('salary_change', 'Income change'), ('cashflow_risk', 'Cash flow risk'), ('subscription_review', 'Subscription review'), ('goal_recommendation', 'Goal recommendation'), ('debt_recommendation', 'Debt recommendation'), ('health_improvement', 'Financial health'), ('promo_expiry', 'Promotional rate ending'), ('rate_increase', 'Rate increase'), ('refinance_opportunity', 'Refinancing opportunity'), ('high_fees', 'High fees'), ('offset_opportunity', 'Offset opportunity'), ('debt_milestone', 'Debt milestone')], max_length=32),
        ),
    ]
