# Generated by Django 5.2.16 on 2026-07-23 07:48

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_lifecycle_and_presentation'),
        ('intelligence', '0004_alter_insight_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('key', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=160)),
                ('category_counts', models.JSONField(blank=True, default=dict)),
                ('seen_descriptors', models.JSONField(blank=True, default=list)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('total_amount_minor', models.BigIntegerField(default=0)),
                ('first_seen_on', models.DateField(blank=True, null=True)),
                ('last_seen_on', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_cadence', models.CharField(blank=True, default='', max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', '-transaction_count'], name='merchant_freq_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'key'), name='uniq_merchant_profile_key')],
            },
        ),
        migrations.CreateModel(
            name='AutomationSuggestion',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('category', 'Category'), ('transfer', 'Transfer'), ('duplicate', 'Possible duplicate'), ('refund', 'Refund'), ('recurring', 'Recurring charge'), ('split', 'Worth splitting'), ('income', 'Income')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_applied', 'Applied automatically')], default='pending', max_length=14)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.CharField(max_length=400)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('merchant_key', models.CharField(blank=True, default='', max_length=120)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by_id', models.UUIDField(blank=True, null=True)),
                ('primary_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.transaction')),
                ('transactions', models.ManyToManyField(blank=True, related_name='automation_suggestions', to='finance.transaction')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status', '-confidence'], name='autosug_queue_idx'), models.Index(fields=['tenant_id', 'kind'], name='autosug_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'dedupe_key'), name='uniq_automation_suggestion'), models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='automation_confidence_range')],
            },
        ),
    ]
