# Generated by Django 5.2.16 on 2026-09-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0008_rls_automationrule_and_suggestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="kind",
            field=models.CharField(
                choices=[
                    ("spending_anomaly", "Spending anomaly"),
                    ("overspending", "Overspending warning"),
                    ("overspend_pace", "On pace to overspend"),
                    ("budget_recommendation", "Budget recommendation"),
                    ("savings_opportunity", "Savings opportunity"),
                    ("duplicate_transaction", "Possible duplicate"),
                    ("large_purchase", "Large purchase"),
                    ("merchant_change", "Merchant price change"),
                    ("salary_change", "Income change"),
                    ("cashflow_risk", "Cash flow risk"),
                    ("subscription_review", "Subscription review"),
                    ("goal_recommendation", "Goal recommendation"),
                    ("debt_recommendation", "Debt recommendation"),
                    ("health_improvement", "Financial health"),
                    ("promo_expiry", "Promotional rate ending"),
                    ("rate_increase", "Rate increase"),
                    ("refinance_opportunity", "Refinancing opportunity"),
                    ("high_fees", "High fees"),
                    ("offset_opportunity", "Offset opportunity"),
                    ("debt_milestone", "Debt milestone"),
                    ("safe_to_spend", "Safe to spend"),
                    ("committed_income", "Committed income"),
                    ("bill_due", "Bill due"),
                ],
                max_length=32,
            ),
        ),
    ]
