# Generated by Django 5.2.16 on 2026-07-23 03:16

import apps.common.ids
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_account_lifecycle_and_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtProfile',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('debt_kind', models.CharField(choices=[('credit_card', 'Credit card'), ('mortgage', 'Mortgage'), ('personal_loan', 'Personal loan'), ('student_loan', 'Student loan'), ('vehicle loan', 'Vehicle loan'), ('bnpl', 'Buy now, pay later'), ('other', 'Other debt')], default='other', max_length=20)),
                ('apr', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('minimum_payment_minor', models.BigIntegerField(default=0)),
                ('payment_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('original_principal_minor', models.BigIntegerField(blank=True, null=True)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('promotional_apr_until', models.DateField(blank=True, null=True)),
                ('promotional_apr', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('custom_priority', models.PositiveSmallIntegerField(default=100)),
                ('include_in_payoff', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('financial_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt_profile', to='finance.financialaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'include_in_payoff'], name='debt_payoff_idx'), models.Index(fields=['tenant_id', 'debt_kind'], name='debt_kind_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('apr__gte', 0)), name='debt_apr_non_negative'), models.CheckConstraint(condition=models.Q(('minimum_payment_minor__gte', 0)), name='debt_min_non_negative'), models.CheckConstraint(condition=models.Q(('payment_day__isnull', True), models.Q(('payment_day__gte', 1), ('payment_day__lte', 28)), _connector='OR'), name='debt_payment_day_range')],
            },
        ),
    ]
