# Generated by Django 5.2.16 on 2026-07-23 04:44

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0002_rls_debt_tables'),
        ('finance', '0003_account_lifecycle_and_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtRateHistory',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('effective_from', models.DateField()),
                ('apr', models.DecimalField(decimal_places=3, max_digits=6)),
                ('source', models.CharField(choices=[('manual', 'Entered manually'), ('statement', 'From a statement'), ('lender', 'Lender notification'), ('promotional', 'Promotional period'), ('index', 'Tracked index change')], default='manual', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'debt rate histories',
                'ordering': ['effective_from'],
            },
        ),
        migrations.AddField(
            model_name='debtprofile',
            name='annual_fee_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debtprofile',
            name='annual_fee_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtprofile',
            name='compounding',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('continuous', 'Continuous')], default='monthly', max_length=12),
        ),
        migrations.AddField(
            model_name='debtprofile',
            name='monthly_fee_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debtprofile',
            name='offset_accounts',
            field=models.ManyToManyField(blank=True, related_name='offsetting_debts', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='debtprofile',
            name='origination_fee_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='debtprofile',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_fee_minor__gte', 0), ('annual_fee_minor__gte', 0), ('origination_fee_minor__gte', 0)), name='debt_fees_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='debtprofile',
            constraint=models.CheckConstraint(condition=models.Q(('annual_fee_month__isnull', True), models.Q(('annual_fee_month__gte', 1), ('annual_fee_month__lte', 12)), _connector='OR'), name='debt_annual_fee_month_range'),
        ),
        migrations.AddField(
            model_name='debtratehistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='debt.debtprofile'),
        ),
        migrations.AddIndex(
            model_name='debtratehistory',
            index=models.Index(fields=['tenant_id', 'profile', '-effective_from'], name='rate_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtratehistory',
            constraint=models.CheckConstraint(condition=models.Q(('apr__gte', 0)), name='rate_history_apr_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='debtratehistory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'profile', 'effective_from'), name='uniq_rate_per_profile_date'),
        ),
    ]
