# Generated by Django 5.2.16 on 2026-08-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0004_rls_rate_history'),
        ('finance', '0005_financialaccount_overdraft_limit_minor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtprofile',
            name='credit_limit_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtprofile',
            name='interest_method',
            field=models.CharField(choices=[('reducing', 'Reducing balance'), ('flat', 'Flat rate')], default='reducing', max_length=10),
        ),
        migrations.AddField(
            model_name='debtprofile',
            name='statement_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtprofile',
            name='term_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='debtprofile',
            constraint=models.CheckConstraint(condition=models.Q(('term_months__isnull', True), ('term_months__gt', 0), _connector='OR'), name='debt_term_positive'),
        ),
        migrations.AddConstraint(
            model_name='debtprofile',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit_minor__isnull', True), ('credit_limit_minor__gt', 0), _connector='OR'), name='debt_credit_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='debtprofile',
            constraint=models.CheckConstraint(condition=models.Q(('statement_day__isnull', True), models.Q(('statement_day__gte', 1), ('statement_day__lte', 28)), _connector='OR'), name='debt_statement_day_in_range'),
        ),
    ]
