# Generated by Django 5.2.16 on 2026-07-18 05:03

import apps.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_currency", models.CharField(max_length=3)),
                ("quote_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=12, max_digits=24)),
                ("as_of", models.DateTimeField(db_index=True)),
                ("source", models.CharField(max_length=40)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["base_currency", "quote_currency", "-as_of"],
                        name="fx_exchange_base_cu_52c47c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("base_currency", "quote_currency", "as_of", "source"),
                        name="uniq_rate_pair_time_source",
                    ),
                    models.CheckConstraint(condition=models.Q(("rate__gt", 0)), name="rate_positive"),
                ],
            },
        ),
    ]
