# Generated by Django 5.2.16 on 2026-09-10 22:50

from django.db import migrations, models


def seed_catalog(apps, schema_editor):
    Currency = apps.get_model("fx", "Currency")
    from apps.fx.currencies import SEED_CURRENCIES

    for item in SEED_CURRENCIES:
        Currency.objects.get_or_create(
            code=item.code,
            defaults={
                "name": item.name,
                "symbol": item.symbol,
                "digits": item.digits,
                "is_active": item.is_active,
                "sort_order": item.sort_order,
            },
        )


def unseed_catalog(apps, schema_editor):
    from apps.fx.currencies import SEED_CURRENCIES

    apps.get_model("fx", "Currency").objects.filter(
        code__in=[item.code for item in SEED_CURRENCIES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("fx", "0002_seed_rates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=3, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("symbol", models.CharField(max_length=12)),
                ("digits", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("code__regex", "^[A-Z]{3}$")),
                        name="fx_currency_iso4217",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("digits__lte", 4)),
                        name="fx_currency_digits_range",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_catalog, unseed_catalog),
    ]
