#!/usr/bin/env python3
"""Capture the landing page's dashboard preview from the running application.

Why this is a script and not a hand-placed asset
------------------------------------------------
The preview on the landing page used to be a token-built abstraction, on the
argument that a screenshot goes stale, cannot follow the visitor's colour
scheme, and puts figures on the page. Those are real objections, and each one
is answered here rather than avoided:

* **stale** — the shot is regenerated by running this script, so it is a build
  step rather than a thing someone remembers to redo. If the dashboard changes
  and nobody reruns it, `--check` fails in CI.
* **colour scheme** — both themes are captured, and the page swaps between them
  with CSS, so the preview follows the visitor the way the rest of the site
  does.
* **figures** — the source is the seeded demo tenant, which is what every
  screen in this repo's fixtures already shows. The alt text says so, in those
  words, so nothing on the page implies the numbers belong to a customer.

What it produces
----------------
Two WebP files in `frontend/app/public/`, cropped to the interesting part of
the Overview screen — the greeting, the net-worth card and the health card —
rather than a full-page shot, which at landing-page display size would be an
unreadable smear.

    python scripts/capture_preview.py            # capture and write
    python scripts/capture_preview.py --check    # fail if the shot is stale

`--check` re-captures to a temporary file and compares against what is
committed, allowing a small pixel tolerance for antialiasing differences
between machines. It is deliberately not byte-exact: font rasterisation is not
reproducible across hosts, and a check that fails on every developer's machine
gets deleted within a week.
"""
from __future__ import annotations

import argparse
import io
import pathlib
import subprocess
import sys
import tempfile

from PIL import Image, ImageChops
from playwright.sync_api import sync_playwright

BASE_URL = "http://localhost:5173"
DEMO_USER = ("amina@example.test", "PlatformAdmin!2026")
OUT_DIR = pathlib.Path(__file__).resolve().parent.parent / "frontend/app/public"
STEM = "preview-dashboard"

#: Captured at 2x for retina, then displayed at roughly half. The crop is in
#: CSS pixels and covers the greeting through the bottom of the two hero cards.
VIEWPORT = {"width": 1180, "height": 820}
SCALE = 2
#: x=232 skips the nav rail: at landing-page display size the rail is an
#: illegible grey stripe, and the cards are the part worth showing. The height
#: ends just below the two hero cards rather than part-way into the next row —
#: a crop through a label reads as a broken image, not as a crop.
CLIP = {"x": 232, "y": 0, "width": 948, "height": 412}

#: WebP quality. 82 is where this particular image stops improving visibly —
#: it is mostly flat surface and text, which WebP handles well.
QUALITY = 82

#: Per-pixel tolerance for --check. Text antialiasing differs between hosts,
#: so a strict comparison would fail everywhere.
MAX_MEAN_DIFF = 6.0


def login(page, email: str, password: str) -> None:
    page.goto(f"{BASE_URL}/login", wait_until="networkidle")
    page.fill("input[type=email]", email)
    page.fill("input[type=password]", password)
    page.click("button[type=submit]")
    page.wait_for_timeout(2500)


def capture(page, theme: str) -> bytes:
    """One themed PNG of the Overview screen, as bytes."""
    page.evaluate(
        """(t) => {
            document.documentElement.dataset.theme = t;
            localStorage.setItem('lf-theme', t);
        }""",
        theme,
    )
    page.goto(f"{BASE_URL}/", wait_until="networkidle")

    # The first version of this script pointed at `/dashboard`, which is not a
    # route, and produced a perfectly good 8 KB screenshot of the 404 page. A
    # capture step has no way to notice that on its own, so it is asserted.
    landed = page.evaluate(
        """() => ({
            status: !!document.querySelector('.lf-status-body, .lf-status-page'),
            greeting: !!document.querySelector('.lf-dash-greeting'),
        })"""
    )
    if landed["status"] or not landed["greeting"]:
        raise RuntimeError("did not land on the dashboard — nothing to capture")

    # The onboarding checklist is a state of *this* tenant, not a feature of the
    # product, and it pushes the cards out of the crop. Same for any toast.
    page.evaluate(
        """() => {
            for (const sel of ['.lf-onboard', '.lf-toast-viewport']) {
                document.querySelectorAll(sel).forEach((n) => n.remove());
            }
        }"""
    )
    # Fonts must be resolved before the shot or the capture races the swap and
    # lands on the fallback face — which is the whole point of self-hosting them.
    page.evaluate("() => document.fonts.ready")
    page.wait_for_timeout(600)
    return page.screenshot(clip=CLIP)


def to_webp(png: bytes) -> bytes:
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as f:
        f.write(png)
        src = f.name
    dst = src.replace(".png", ".webp")
    subprocess.run(["cwebp", "-quiet", "-q", str(QUALITY), src, "-o", dst], check=True)
    return pathlib.Path(dst).read_bytes()


def differs(a: bytes, b: bytes) -> float | None:
    """Mean per-channel difference, or None if the images are not comparable."""
    ia = Image.open(io.BytesIO(a)).convert("RGB")
    ib = Image.open(io.BytesIO(b)).convert("RGB")
    if ia.size != ib.size:
        return None
    diff = ImageChops.difference(ia, ib)
    hist = diff.histogram()
    total = sum(i % 256 * n for i, n in enumerate(hist))
    return total / (ia.width * ia.height * 3)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed shot is stale")
    args = ap.parse_args()

    shots: dict[str, bytes] = {}
    with sync_playwright() as p:
        browser = p.chromium.launch()
        ctx = browser.new_context(viewport=VIEWPORT, device_scale_factor=SCALE)
        page = ctx.new_page()
        login(page, *DEMO_USER)
        for theme in ("light", "dark"):
            shots[theme] = to_webp(capture(page, theme))
        browser.close()

    failed = False
    for theme, data in shots.items():
        path = OUT_DIR / f"{STEM}-{theme}.webp"
        if args.check:
            if not path.exists():
                print(f"  MISSING  {path.name}")
                failed = True
                continue
            mean = differs(path.read_bytes(), data)
            if mean is None:
                print(f"  RESIZED  {path.name} — crop geometry changed")
                failed = True
            elif mean > MAX_MEAN_DIFF:
                print(f"  STALE    {path.name} — mean diff {mean:.2f} > {MAX_MEAN_DIFF}")
                failed = True
            else:
                print(f"  OK       {path.name} — mean diff {mean:.2f}")
        else:
            path.write_bytes(data)
            print(f"  wrote    {path.name}  {len(data) / 1024:.0f} KB")

    if args.check and failed:
        print("\nThe landing preview no longer matches the dashboard.")
        print("Run: python scripts/capture_preview.py")
        return 1
    print("\nLanding preview up to date." if args.check else "\nCaptured.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
