# Generated by Django 5.2.16 on 2026-07-18 05:03

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("starts_on", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "is_active"], name="budgeting_b_tenant__c6068c_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("limit_minor", models.BigIntegerField()),
                ("rollover", models.BooleanField(default=False)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="budgeting.budget",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_lines",
                        to="finance.category",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("budget", "category"),
                        name="uniq_budget_category",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("limit_minor__gte", 0)), name="budget_limit_nonneg"
                    ),
                ],
            },
        ),
    ]
