# Generated by Django 5.2.16 on 2026-08-03 16:29

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0004_transaction_reconciled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('employment', 'Employment'), ('self_employment', 'Self-employment'), ('business', 'Business'), ('rental', 'Rental'), ('pension', 'Pension'), ('benefits', 'Benefits or grant'), ('investment', 'Investment income'), ('other', 'Other')], default='employment', max_length=20)),
                ('payer', models.CharField(blank=True, default='', max_length=120)),
                ('currency', models.CharField(max_length=3)),
                ('net_minor', models.BigIntegerField()),
                ('gross_minor', models.BigIntegerField(blank=True, null=True)),
                ('reliability', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Varies'), ('irregular', 'Irregular')], default='fixed', max_length=12)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Every two weeks'), ('semi_monthly', 'Twice a month'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annually'), ('ad_hoc', 'Whenever it comes')], default='monthly', max_length=14)),
                ('pay_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('second_pay_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_sources', to='finance.financialaccount')),
                ('recurring_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_source', to='finance.recurringtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeReceipt',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('occurred_on', models.DateField()),
                ('net_minor', models.BigIntegerField()),
                ('gross_minor', models.BigIntegerField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_receipts', to='finance.transaction')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='income.incomesource')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeDeduction',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('tax', 'Income tax'), ('social_security', 'Social security'), ('pension', 'Pension'), ('health', 'Health insurance'), ('loan', 'Loan repayment'), ('union', 'Union or association'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('percent_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='income.incomesource')),
            ],
        ),
        migrations.AddIndex(
            model_name='incomesource',
            index=models.Index(fields=['tenant_id', 'is_active'], name='income_active_idx'),
        ),
        migrations.AddIndex(
            model_name='incomesource',
            index=models.Index(fields=['tenant_id', 'kind'], name='income_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='incomesource',
            constraint=models.CheckConstraint(condition=models.Q(('net_minor__gt', 0)), name='income_net_positive'),
        ),
        migrations.AddConstraint(
            model_name='incomesource',
            constraint=models.CheckConstraint(condition=models.Q(('gross_minor__isnull', True), ('gross_minor__gt', 0), _connector='OR'), name='income_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='incomesource',
            constraint=models.CheckConstraint(condition=models.Q(('gross_minor__isnull', True), ('net_minor__lte', models.F('gross_minor')), _connector='OR'), name='income_net_not_above_gross'),
        ),
        migrations.AddConstraint(
            model_name='incomesource',
            constraint=models.CheckConstraint(condition=models.Q(('pay_day__isnull', True), models.Q(('pay_day__gte', 1), ('pay_day__lte', 28)), _connector='OR'), name='income_pay_day_in_range'),
        ),
        migrations.AddConstraint(
            model_name='incomesource',
            constraint=models.CheckConstraint(condition=models.Q(('second_pay_day__isnull', True), models.Q(('second_pay_day__gte', 1), ('second_pay_day__lte', 28)), _connector='OR'), name='income_second_pay_day_in_range'),
        ),
        migrations.AddConstraint(
            model_name='incomesource',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='income_ends_after_start'),
        ),
        migrations.AddIndex(
            model_name='incomereceipt',
            index=models.Index(fields=['tenant_id', 'source', '-occurred_on'], name='income_receipt_hist_idx'),
        ),
        migrations.AddIndex(
            model_name='incomereceipt',
            index=models.Index(fields=['tenant_id', '-occurred_on'], name='income_receipt_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='incomereceipt',
            constraint=models.CheckConstraint(condition=models.Q(('net_minor__gt', 0)), name='receipt_net_positive'),
        ),
        migrations.AddConstraint(
            model_name='incomereceipt',
            constraint=models.CheckConstraint(condition=models.Q(('gross_minor__isnull', True), ('gross_minor__gt', 0), _connector='OR'), name='receipt_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='incomereceipt',
            constraint=models.CheckConstraint(condition=models.Q(('gross_minor__isnull', True), ('net_minor__lte', models.F('gross_minor')), _connector='OR'), name='receipt_net_not_above_gross'),
        ),
        migrations.AddIndex(
            model_name='incomededuction',
            index=models.Index(fields=['tenant_id', 'source'], name='income_deduction_src_idx'),
        ),
        migrations.AddConstraint(
            model_name='incomededuction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_minor__isnull', False), ('percent_bp__isnull', True)), models.Q(('amount_minor__isnull', True), ('percent_bp__isnull', False)), _connector='OR'), name='deduction_exactly_one_basis'),
        ),
        migrations.AddConstraint(
            model_name='incomededuction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__isnull', True), ('amount_minor__gt', 0), _connector='OR'), name='deduction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='incomededuction',
            constraint=models.CheckConstraint(condition=models.Q(('percent_bp__isnull', True), models.Q(('percent_bp__gt', 0), ('percent_bp__lte', 10000)), _connector='OR'), name='deduction_percent_in_range'),
        ),
    ]
