# Generated by Django 5.2.16 on 2026-08-04 17:22

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssumptionSet',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('annual_inflation', models.DecimalField(decimal_places=4, default='0.0500', max_digits=6)),
                ('annual_salary_growth', models.DecimalField(decimal_places=4, default='0.0300', max_digits=6)),
                ('annual_investment_return', models.DecimalField(decimal_places=4, default='0.0700', max_digits=6)),
                ('annual_cash_return', models.DecimalField(decimal_places=4, default='0.0000', max_digits=6)),
                ('effective_tax_rate', models.DecimalField(decimal_places=4, default='0.0000', max_digits=6)),
                ('annual_property_growth', models.DecimalField(decimal_places=4, default='0.0400', max_digits=6)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'is_default'], name='assumption_default_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'name'), name='uniq_assumption_set_name'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('tenant_id',), name='uniq_default_assumption_set')],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('visibility', models.CharField(choices=[('private', 'Only me'), ('household', 'Shared with the household')], default='private', max_length=12)),
                ('horizon_months', models.PositiveSmallIntegerField(default=120)),
                ('assumption_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='projections.assumptionset')),
                ('duplicated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='projections.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioEvent',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('home_purchase', 'Buying a home'), ('mortgage', 'Taking a mortgage'), ('vehicle_purchase', 'Buying a vehicle'), ('job_change', 'Changing jobs'), ('salary_increase', 'A pay rise'), ('job_loss', 'Losing employment'), ('hours_reduction', 'Reducing working hours'), ('debt_payoff', 'Paying off debt'), ('invest_more', 'Investing more'), ('new_child', 'A new child'), ('retirement', 'Retiring'), ('education', 'Education costs'), ('relocation', 'Relocating'), ('business_start', 'Starting a business'), ('one_time_purchase', 'A large one-off purchase')], max_length=32)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('start_month', models.PositiveSmallIntegerField(default=1)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projections.scenario')),
            ],
            options={
                'ordering': ['sort_order', 'start_month'],
            },
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['tenant_id', 'status'], name='scenario_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['tenant_id', 'visibility'], name='scenario_visibility_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'name'), name='uniq_scenario_name'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.CheckConstraint(condition=models.Q(('horizon_months__gte', 1), ('horizon_months__lte', 480)), name='scenario_horizon_in_range'),
        ),
        migrations.AddIndex(
            model_name='scenarioevent',
            index=models.Index(fields=['tenant_id', 'scenario'], name='scenario_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenarioevent',
            constraint=models.CheckConstraint(condition=models.Q(('start_month__gte', 1), ('start_month__lte', 480)), name='scenario_event_start_in_range'),
        ),
    ]
