# Generated by Django 5.2.16 on 2026-08-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0002_rls_projection_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioevent',
            name='kind',
            field=models.CharField(choices=[('home_purchase', 'Buying a home'), ('mortgage', 'Taking a mortgage'), ('vehicle_purchase', 'Buying a vehicle'), ('job_change', 'Changing jobs'), ('salary_increase', 'A pay rise'), ('job_loss', 'Losing employment'), ('hours_reduction', 'Reducing working hours'), ('debt_payoff', 'Paying off debt'), ('invest_more', 'Investing more'), ('new_child', 'A new child'), ('retirement', 'Retiring'), ('education', 'Education costs'), ('relocation', 'Relocating'), ('business_start', 'Starting a business'), ('one_time_purchase', 'A large one-off purchase'), ('marriage', 'Getting married'), ('parental_leave', 'Parental leave'), ('separation', 'Separating or divorcing'), ('caring_for_parent', 'Caring for a parent'), ('inheritance', 'An inheritance')], max_length=32),
        ),
    ]
