# Generated by Django 5.2.16 on 2026-09-21 14:01

import apps.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0003_alter_scenarioevent_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumptionset',
            name='annual_expense_ratio',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=6),
        ),
        migrations.AddField(
            model_name='assumptionset',
            name='annual_inflation_volatility',
            field=models.DecimalField(decimal_places=4, default='0.0200', max_digits=6),
        ),
        migrations.AddField(
            model_name='assumptionset',
            name='annual_return_volatility',
            field=models.DecimalField(decimal_places=4, default='0.1500', max_digits=6),
        ),
        migrations.CreateModel(
            name='PlanningProfile',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('target_fi_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monthly_spend_override_minor', models.BigIntegerField(blank=True, null=True)),
                ('safe_withdrawal_rate', models.DecimalField(decimal_places=4, default='0.0400', max_digits=6)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id',), name='uniq_planning_profile'), models.CheckConstraint(condition=models.Q(('monthly_spend_override_minor__isnull', True), ('monthly_spend_override_minor__gt', 0), _connector='OR'), name='planning_spend_positive'), models.CheckConstraint(condition=models.Q(('safe_withdrawal_rate__gt', 0), ('safe_withdrawal_rate__lte', '0.2000')), name='planning_swr_in_range'), models.CheckConstraint(condition=models.Q(('target_fi_year__isnull', True), models.Q(('target_fi_year__gte', 2000), ('target_fi_year__lte', 2200)), _connector='OR'), name='planning_fi_year_sane')],
            },
        ),
    ]
