# Generated by Django 5.2.16 on 2026-10-09 06:51

import apps.common.ids
import apps.projections.share_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projections", "0006_alter_scenarioevent_kind"),
        ("tenancy", "0007_tenant_block_overdrafts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64)),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("payload", models.JSONField()),
                (
                    "expires_at",
                    models.DateTimeField(default=apps.projections.share_models._default_share_expiry),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decision_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_shares",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["expires_at"], name="projections_expires_f2da7d_idx")],
            },
        ),
    ]
