# Generated by Django 5.2.16 on 2026-07-18 10:22

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0002_transaction_split_group_bill"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=120)),
                ("currency", models.CharField(max_length=3)),
                ("target_minor", models.BigIntegerField()),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "tracking",
                    models.CharField(
                        choices=[
                            ("manual", "Manual contributions"),
                            ("account_balance", "Linked account balance"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("achieved", "Achieved"), ("archived", "Archived")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                (
                    "linked_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="savings_goals",
                        to="finance.financialaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoalContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("amount_minor", models.BigIntegerField()),
                ("occurred_on", models.DateField()),
                ("memo", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goal_contributions",
                        to="finance.transaction",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="goals.savingsgoal",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="savingsgoal",
            index=models.Index(fields=["tenant_id", "status"], name="goal_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="savingsgoal",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_minor__gt", 0)), name="goal_target_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="goalcontribution",
            index=models.Index(fields=["tenant_id", "goal", "-occurred_on"], name="goal_contrib_idx"),
        ),
        migrations.AddConstraint(
            model_name="goalcontribution",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_minor__gt", 0)), name="goal_contribution_positive"
            ),
        ),
    ]
