# Generated by Django 5.2.16 on 2026-07-22 13:17

"""Goal taxonomy, priority, funding plan, and auto-contribution rules.

Purely additive with safe defaults — existing goals become CUSTOM kind at
MEDIUM priority with no funding plan, which is exactly how they behaved before.
Zero-downtime.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_lifecycle_and_presentation'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='auto_contribute_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='auto_contribute_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='auto_contribute_last_run_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='auto_contribute_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='kind',
            field=models.CharField(choices=[('emergency_fund', 'Emergency fund'), ('vacation', 'Vacation'), ('house_deposit', 'House deposit'), ('education', 'Education'), ('retirement', 'Retirement'), ('vehicle', 'Vehicle purchase'), ('debt_payoff', 'Debt payoff'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='planned_monthly_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Someday')], default=3),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('achieved', 'Achieved'), ('archived', 'Archived')], default='active', max_length=12),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['tenant_id', 'priority', 'target_date'], name='goal_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['tenant_id', 'kind'], name='goal_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('planned_monthly_minor__isnull', True), ('planned_monthly_minor__gt', 0), _connector='OR'), name='goal_planned_monthly_positive'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('auto_contribute_minor__isnull', True), ('auto_contribute_minor__gt', 0), _connector='OR'), name='goal_auto_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('auto_contribute_day__isnull', True), models.Q(('auto_contribute_day__gte', 1), ('auto_contribute_day__lte', 28)), _connector='OR'), name='goal_auto_day_in_range'),
        ),
    ]
