# Generated by Django 5.2.16 on 2026-08-04 18:40

import apps.common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0004_transaction_reconciled_at'),
        ('tenancy', '0005_tenantaisettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSharing',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('policy', models.CharField(choices=[('private', 'Only me'), ('shared', 'Shared with the household'), ('read_only', 'Household can see, only I can change'), ('approval_required', 'Changes need my approval')], default='private', max_length=24)),
                ('is_joint', models.BooleanField(default=False)),
                ('financial_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sharing', to='finance.financialaccount')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_accounts', to='tenancy.membership')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('summary', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('account_sharing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='household.accountsharing')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_change_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_change_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(choices=[('self', 'Me'), ('partner', 'Partner or spouse'), ('child', 'Child'), ('parent', 'Parent'), ('other', 'Other')], default='child', max_length=16)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monthly_cost_minor', models.BigIntegerField(blank=True, null=True)),
                ('support_until_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'relationship'], name='dependant_rel_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_cost_minor__isnull', True), ('monthly_cost_minor__gte', 0), _connector='OR'), name='dependant_cost_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='HouseholdProfile',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('relationship', models.CharField(choices=[('self', 'Me'), ('partner', 'Partner or spouse'), ('child', 'Child'), ('parent', 'Parent'), ('other', 'Other')], default='self', max_length=16)),
                ('contribution_share', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_profile', to='tenancy.membership')),
            ],
        ),
        migrations.AddIndex(
            model_name='accountsharing',
            index=models.Index(fields=['tenant_id', 'owner'], name='sharing_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsharing',
            index=models.Index(fields=['tenant_id', 'policy'], name='sharing_policy_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['tenant_id', 'status'], name='change_request_status_idx'),
        ),
        migrations.AddIndex(
            model_name='householdprofile',
            index=models.Index(fields=['tenant_id', 'relationship'], name='household_rel_idx'),
        ),
    ]
