# Generated by Django 5.2.16 on 2026-08-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_rls_household_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='created_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='updated_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
