# Generated by Django 5.2.16 on 2026-08-06 10:47

import apps.common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_changerequest_created_by_id_and_more'),
        ('tenancy', '0007_tenant_block_overdrafts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionAgreement',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('mode', models.CharField(default='equal', max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('target_minor', models.BigIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('review_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['tenant_id', 'superseded_at'], name='contrib_agreement_live_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('actor_label', models.CharField(blank=True, default='', max_length=120)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('approved', 'Approved'), ('declined', 'Declined'), ('shared', 'Sharing changed'), ('contributed', 'Contributed'), ('paid', 'Paid'), ('invited', 'Invited'), ('joined', 'Joined')], max_length=16)),
                ('subject_type', models.CharField(max_length=40)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('is_private', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', '-created_at'], name='audit_recent_idx'), models.Index(fields=['tenant_id', 'subject_type', 'subject_id'], name='audit_subject_idx'), models.Index(fields=['tenant_id', 'action'], name='audit_action_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContributionTerm',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('fixed_minor', models.BigIntegerField(blank=True, null=True)),
                ('share', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='household.contributionagreement')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_terms', to='tenancy.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('agreement', 'membership'), name='uniq_term_per_member'), models.CheckConstraint(condition=models.Q(('fixed_minor__isnull', True), ('fixed_minor__gte', 0), _connector='OR'), name='contribution_fixed_non_negative')],
            },
        ),
    ]
