# Generated by Django 5.2.16 on 2026-08-06 10:59

import apps.common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financialaccount_overdraft_limit_minor_and_more'),
        ('household', '0005_rls_contribution_and_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('scope', models.CharField(choices=[('joint', 'Money from joint accounts'), ('shared', 'Anything the household can see'), ('account', 'One specific account')], default='joint', max_length=12)),
                ('currency', models.CharField(max_length=3)),
                ('min_amount_minor', models.BigIntegerField()),
                ('expires_after_hours', models.PositiveIntegerField(default=48)),
                ('is_active', models.BooleanField(default=True)),
                ('financial_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='finance.financialaccount')),
            ],
            options={
                'ordering': ['-min_amount_minor'],
            },
        ),
        migrations.CreateModel(
            name='SpendApproval',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('requested', 'Asked before spending'), ('flagged', 'Noticed after the money moved')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Nobody answered'), ('withdrawn', 'Withdrawn by the requester')], default='pending', max_length=12)),
                ('requested_by_label', models.CharField(blank=True, default='', max_length=120)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=255)),
                ('suggested_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_label', models.CharField(blank=True, default='', max_length=120)),
                ('financial_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.financialaccount')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_approvals_resolved', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='household.approvalrule')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalComment',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('author_label', models.CharField(blank=True, default='', max_length=120)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='household.spendapproval')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['tenant_id', 'is_active'], name='approval_rule_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount_minor__gt', 0)), name='approval_rule_threshold_positive'),
        ),
        migrations.AddIndex(
            model_name='spendapproval',
            index=models.Index(fields=['tenant_id', 'status'], name='spend_approval_status_idx'),
        ),
        migrations.AddIndex(
            model_name='spendapproval',
            index=models.Index(fields=['tenant_id', '-created_at'], name='spend_approval_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='spendapproval',
            index=models.Index(fields=['tenant_id', 'expires_at'], name='spend_approval_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalcomment',
            index=models.Index(fields=['tenant_id', 'approval'], name='approval_comment_idx'),
        ),
    ]
