# Generated by Django 5.2.16 on 2026-08-06 11:11

import apps.common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financialaccount_overdraft_limit_minor_and_more'),
        ('household', '0007_rls_approval_tables'),
        ('tenancy', '0007_tenant_block_overdrafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPrivacy',
            fields=[
                ('id', models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('level', models.CharField(choices=[('private', 'Not shown to anyone else'), ('category_only', 'They see the category, not the amount'), ('amount_only', 'They see the amount, not what it was for'), ('full', 'Fully visible')], default='private', max_length=16)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to='finance.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'level'], name='txn_privacy_level_idx'), models.Index(fields=['tenant_id', 'owner'], name='txn_privacy_owner_idx')],
            },
        ),
    ]
