# Generated by Django 5.2.16 on 2026-07-18 10:20

import apps.common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("budget_threshold", "Budget threshold reached"),
                            ("budget_exceeded", "Budget exceeded"),
                            ("low_balance", "Low account balance"),
                            ("large_transaction", "Large transaction"),
                            ("anomaly", "Unusual activity"),
                            ("bill_due", "Bill due soon"),
                            ("bill_overdue", "Bill overdue"),
                            ("goal_achieved", "Goal achieved"),
                            ("goal_milestone", "Goal milestone"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("critical", "Critical")],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, default="", max_length=500)),
                ("subject_type", models.CharField(blank=True, default="", max_length=40)),
                ("subject_id", models.UUIDField(blank=True, null=True)),
                ("dedupe_key", models.CharField(blank=True, default="", max_length=200)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_channels", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "user", "-created_at"], name="notif_inbox_idx"),
                    models.Index(
                        condition=models.Q(("read_at__isnull", True)),
                        fields=["tenant_id", "-created_at"],
                        name="notif_unread_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key", ""), _negated=True),
                        fields=("tenant_id", "dedupe_key"),
                        name="uniq_notification_dedupe",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("created_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("muted_types", models.JSONField(blank=True, default=list)),
                ("budget_threshold", models.FloatField(default=0.9)),
                ("low_balance_minor", models.BigIntegerField(blank=True, null=True)),
                ("large_transaction_minor", models.BigIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant_id", "user"), name="uniq_notif_pref_user")
                ],
            },
        ),
    ]
