# Generated by Django 5.2.16 on 2026-07-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_remove_pushsubscription_uniq_push_subscription_endpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="monthly_summary",
            field=models.BooleanField(default=True),
        ),
    ]
