# Generated by Django 5.2.16 on 2026-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_email_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='weekly_digest',
            field=models.BooleanField(default=True),
        ),
    ]
